version: 2
updates:
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily
    ignore:
      - dependency-name: "mike"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    ignore:
      - dependency-name: "@middy/core"
        update-types: [ "version-update:semver-major" ]
    groups:
      aws-sdk:
        patterns:
        - "@aws-sdk/**"
        - "aws-sdk-client-mock"
        - "aws-sdk-client-mock-jest"
      aws-cdk:
        patterns:
        - "@aws-cdk/**"
        - "aws-cdk-lib"
