tasks:
  - init: |
      # Install Nodejs version specified in .nvmrc
      bash -c ". ~/.nvm/nvm.sh \
        && nvm install \
        && nvm alias default"
      # Install AWS SAM CLI
      wget -q https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      unzip -q aws-sam-cli-linux-x86_64.zip -d sam-installation
      sudo ./sam-installation/install
      rm -rf sam-installation aws-sam-cli-linux-*
      # Install repo dependencies
      npm run setup-local
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - firsttris.vscode-jest-runner
