version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "powertools-sam-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bflpel1nfslg"
s3_prefix = "powertools-sam-2"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
