name: install-dependencies
on:
  workflow_call: {}
jobs:
  install-dependencies:
    name: Install all dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Use NodeJS 14"
        uses: actions/setup-node@v3
        with:
          # Always use version 14 as we use TypeScript target es2020
          node-version: 14
      - name: "Install npm@8.x"
        run: npm i -g npm@next-8
      - name: "Install monorepo packages"
        # This installs all the dependencies of ./packages/*
        # See https://github.com/npm/cli/issues/4475 to see why --foreground-scripts
        run: npm ci --foreground-scripts