name: Manual publish docs

on:
  workflow_dispatch: {}

jobs:
  run-unit-tests:
    uses: ./.github/workflows/reusable-publish-docs.yml
    with:
      workflow_origin: ${{ github.event.repository.full_name }}
      isRelease: "true"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
