name: Auto publish docs to version "main"

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'mkdocs.yml'
      - '.github/workflows/on-docs-change.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.8'
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '17.2'
      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install -r docs/requirements.txt
          npm ci
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Build mkdocs site in "gh-pages" branch and push
        run: |
          rm -rf site
          VERSION="main"
          ALIAS="stage"
          mkdocs build
          mike deploy --push --update-aliases "$VERSION" "$ALIAS"
      - name: Build API documentation site 
        run: |
          rm -rf api
          npm run docs-generateApiDoc
      - name: Release API docs to the main version
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
          keep_files: true
          destination_dir: main/api 