name: Publish new doc on gh-pages branch

on:
  push:
    branches:
      - feat/github-workflow-publish-doc
    paths:
      - 'docs/**'
      - 'CHANGELOG.md'
      - 'mkdocs.yml'
      - 'package.json'
      - '.github/workflows/on-docs-change.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.8"
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.18'
      - name: Install dependencies
        run: |
          pip install --upgrade pip 
          pip install mike==1.1.2
          npm install
      - name: Setup doc deploy
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Build mkdocs image
        uses: docker/build-push-action@v2
        with:
          context: ./docs
          push: false
          tags: awslabs/aws-lambda-powertool-typescript-docs:build
      - name: Build docs website and (TODO) API reference 
        run: |
          VERSION="develop"
          ALIAS="stage"
          echo "PWD = ${PWD}"
          docker run --rm -v ${PWD}:/docs awslabs/aws-lambda-powertool-typescript-docs:build build
          mike deploy --push --update-aliases "$VERSION" "$ALIAS"
      - name: Deploy all docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: true
          destination_dir: develop/api 
      # - name: Create redirect from old docs
      #   run: |
      #     git checkout gh-pages
      #     test -f 404.html && echo "Redirect already set" && exit 0
      #     git checkout develop -- 404.html
      #     git add 404.html
      #     git commit -m "chore: set docs redirect" --no-verify
      #     git push origin gh-pages -f