name: on-push-event
on:
  push

jobs:
  on_push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    env:
      NODE_ENV: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: |
          npm ci
          npm run lerna-ci
      - name: Run lint
        run: npm run lerna-lint
      - name: Run tests
        run: npm run lerna-test