name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  contents: read

jobs:
  release-docs:
    permissions:
      id-token: write  # trade JWT token for AWS credentials in AWS Docs account
      contents: read  # read from this repo to publish docs
    secrets: inherit
    uses: ./.github/workflows/reusable_publish_docs.yml
    with:
      version: main
      alias: stage