name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  contents: read

jobs:
  release-docs:
    permissions:
      actions: write
      id-token: write
    secrets: inherit
    uses: ./.github/workflows/reusable-publish-docs.yml
    with:
      version: main
      alias: stage