name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  release-docs:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: ./.github/workflows/reusable-publish-docs.yml
    with:
      version: main
      alias: stage