name: Monthly roadmap reminder

on:
    workflow_dispatch: {}
    schedule:
      - cron: '0 0 1 * *'  # runs first day of the month

permissions:
    contents: read


jobs:
    monthly-roadmap-reminder:
        permissions:
            contents: read
            pull-requests: read
            issues: write  # create monthly roadmap report
        uses: aws-powertools/actions/.github/workflows/monthly_roadmap_reminder.yml@dd7035996f1813dbc50fe78e523d4c2a074258a9
        secrets:
            token: ${{ secrets.GITHUB_TOKEN }}
