name: pr-lint-and-test

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
  test-utils:
    needs: checkout
    runs-on: ubuntu-latest
    env: NODE_ENV
    strategy:
      matrix:
        version: [12, 14, 16]
      fail-fast: false
    steps:
      - name: "Use NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: Install npm@8.x
        run: npm i -g npm@next-8
      - name: Install monorepo packages
        # This installs all the dependencies of ./packages/*
        # See https://github.com/npm/cli/issues/4475 to see why --foreground-scripts
        run: npm ci --foreground-scripts
      - name: Run lint
        run: npm run lint -ws
      - name: Run tests
        run: npm t -ws
  install-examples:
    needs: checkout
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        example: ["sam", "cdk"]
      fail-fast: false
    defaults:
      run:
        working-directory: ./examples/${{ matrix.example }}
    steps:
      - name: "Use NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm@8.x
        run: npm i -g npm@next-8
      - name: "Install example packages"
        run: npm ci
      - name: "Run tests"
        run: npm t
