name: Test
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.2.11
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
