name: Record PR details

on:
  pull_request:
    types: [opened, edited, closed]

permissions:
  contents: read

jobs:
  record_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab  # v3.5.2
      - name: "Extract PR details"
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const script = require('.github/scripts/save_pr_details.js')
            await script({github, context, core})
      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: pr
          path: pr.txt