name: Update Layer ARN Docs

on:
  workflow_call:
    inputs:
      latest_published_version:
        description: "Latest NPM published version to rebuild latest docs for, e.g. 1.5.1"
        type: string
        required: true

permissions:
  contents: read

env:
  BRANCH: main
  RELEASE_COMMIT: ${{ github.sha }}

jobs:
  publish_layer_arn:
    # Force Github action to run only a single job at a time (based on the group name)
    # This is to prevent race-condition and inconsistencies with changelog push
    concurrency:
      group: changelog-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: none
    steps:
      - name: Checkout repository # reusable workflows start clean, so we need to checkout again
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          ref: ${{ env.RELEASE_COMMIT }}
      - name: Download CDK layer artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: cdk-layer-stack
          path: cdk-layer-stack/
      - name: Replace layer versions in documentation
        run: |
          ls -la cdk-layer-stack/
          ./.github/scripts/update_layer_arn.sh cdk-layer-stack
      - name: Create PR
        id: create-pr
        uses: ./.github/actions/create-pr
        with: 
          files: 'docs/index.md'
          temp_branch_prefix: 'ci-layer-docs'
          pull_request_title: 'chore(ci): update layer ARN on documentation'
          github_token: ${{ secrets.GITHUB_TOKEN }}
  