name: Publish docs

on:
  workflow_call:
    inputs:
      workflow_origin: # see https://github.com/awslabs/aws-lambda-powertools-python/issues/1349
        required: true
        type: string
      prIsMerged:
        required: false
        default: "false"
        type: string
      isRelease:
        required: false
        default: "false"
        type: string
    secrets:
      token:
        required: true

jobs:
  publish-docs:
    # see https://github.com/awslabs/aws-lambda-powertools-python/issues/1349
    if: ${{ inputs.workflow_origin == 'dreamorosi/aws-lambda-powertools-typescript' }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "${{ inputs.workflow_origin }}"
      - name: Debug 2
        if: ${{ inputs.workflow_origin == 'dreamorosi/aws-lambda-powertools-typescript' }}
        run: |
          echo "OK"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Here `token` is needed to avoid incurring in error GH006 Protected  Branch Update Failed,
          token: ${{ secrets.token }}
          # While `fetch-depth` is used to allow the workflow to later commit & push the changes.
          fetch-depth: 0
      - name: Set RELEASE_VERSION env var to `latest`
        if: ${{ inputs.isRelease == 'true' }}
        run: |
          RELEASE_VERSION=$(git describe --abbrev=0 | sed 's/v//')
          echo "RELEASE_VERSION=${RELEASE_VERSION}"
          echo "${{ github.ref_name }}"
          echo "${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
