name: Run unit tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        version: [18, 20]
        workspace: ["packages/batch"]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Setup NodeJS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
        with:
          nodeVersion: ${{ matrix.version }}
          build: false
      - name: Linting
        run: npm run lint -w ${{ matrix.workspace }}
      - name: Unit tests
        run: npm run test:unit:coverage -w ${{ matrix.workspace }}
  run-linting-check-and-unit-tests-on-utilities:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        version: [18, 20]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Setup NodeJS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.version }}
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
        with:
          nodeVersion: ${{ matrix.version }}
      - name: Run linting
        run: |
          npm run lint -w packages/commons \
            -w packages/logger \
            -w packages/tracer \
            -w packages/metrics \
            -w packages/parameters \
            -w packages/idempotency \
            -w packages/batch \
            -w packages/jmespath \
            -w packages/parser \
            -w packages/event-handler
      - name: Run unit tests
        run: |
          npm t -w packages/commons \
            -w packages/logger \
            -w packages/tracer \
            -w packages/metrics \
            -w packages/parameters \
            -w packages/idempotency \
            -w packages/batch \
            -w packages/jmespath \
            -w packages/parser \
            -w packages/event-handler
  check-examples:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    strategy:
      matrix:
        example: ["app"]
      fail-fast: false
    defaults:
      run:
        working-directory: examples/${{ matrix.example }}
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Setup NodeJS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm t
  check-layer-publisher:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Setup NodeJS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint -w layers
      - name: Run tests
        run: npm run test:unit -w layers
  check-docs-snippets:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Setup NodeJS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint -w examples/snippets
  check-docs:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Setup NodeJS
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          cache: "npm"
      - name: Setup dependencies
        uses: aws-powertools/actions/.github/actions/cached-node-modules@d406bac5563f1d8c793519a3eedfe620f6a14872
      - name: Run linting
        run: npm run lint:markdown
