name: test-pkg-size
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ flochaz/pkgSize ]
jobs:
  on_push:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install npm@8.x
        run: npm i -g npm@next-8
      - name: Install monorepo packages
        # This installs all the dependencies of ./packages/*
        # See https://github.com/npm/cli/issues/4475 to see why --foreground-scripts
        run: npm ci --foreground-scripts
      - name: Package size report
        uses: ./.github/actions/pkg-size
        with:
          build-command: npm run package
          work-directory: /packages/metrics
          dist-directory: /packages/metrics/dist
          mode: 'head-only'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
