name: run-e2e-tests
on:
  # workflow_dispatch: {}
  # TODO: remove this. This is just temporary to test matrix strategy w/ e2e tests 
  push:
    branches:
      - chore/run-e2e-multiple-runtimes

jobs:
  run:
    #########################
    # Force Github action to run only a single job at a time (based on the group name)
    # This is to prevent "race-condition" in building e2e tests infrastructure
    #########################
    concurrency:
      group: e2e-tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    strategy:
      matrix:
        nodeRuntime: ['12', '14']
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    # We build and package with latest Lambda runtime stable version (14) so we will stick with it to be consistent.
    - name: "Setup NodeJS 14"
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install packages
      run: |
        npm ci
        npm run lerna-ci
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1.6.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
        aws-region: eu-west-1
    - name: Run integration tests
      run: |
        export RUNTIME=nodejs${{ matrix.nodeRuntime }}x 
        echo $RUNTIME
        npm run lerna-test:e2e
    - name: Test packaging
      run: | 
        npm run lerna-package
        cd examples/cdk
        npm install ../../packages/**/dist/aws-lambda-powertools-*
        npm run test